In [1]:
import joblib
import kagglehub
import modin.pandas as pd
from utils import preprocess_data

# Load dataset (example: historical ticket pricing data)
path = kagglehub.dataset_download("ibrahimelsayed182/plane-ticket-price")
print("Path to dataset files:", path)
data_path = fr'{path}\ticket_pricing_data.csv'
raw = pd.read_csv(r'C:\Users\Alex\.cache\kagglehub\datasets\ibrahimelsayed182\plane-ticket-price\versions\1\Data_Train.csv')

c:\Projects\datasci2\DataSci\.ml\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Path to dataset files: C:\Users\Alex\.cache\kagglehub\datasets\ibrahimelsayed182\plane-ticket-price\versions\1

In [2]:
raw.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [3]:
#select the flights form Kolkata to Banglore
data = raw[raw['Source'] == 'Kolkata']
data = data[data['Destination'] == 'Banglore']
data.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
5,SpiceJet,24/06/2019,Kolkata,Banglore,CCU → BLR,09:00,11:25,2h 25m,non-stop,No info,3873
11,IndiGo,18/04/2019,Kolkata,Banglore,CCU → BLR,20:20,22:55,2h 35m,non-stop,No info,4174
13,Jet Airways,9/05/2019,Kolkata,Banglore,CCU → BOM → BLR,21:10,09:20 10 May,12h 10m,1 stop,In-flight meal not included,9663

In [6]:
#select fligths with a durateion between 6 and 8 hours
data2 = raw[raw['Duration'] >= '6h']
data2 = data2[data2['Duration'] <= '8h']
#get the average price of the flights
average_price = data2['Price'].mean()
print(average_price)

11455.806703910615

In [7]:
data2.head(50)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
9,Multiple carriers,27/05/2019,Delhi,Cochin,DEL → BOM → COK,11:25,19:15,7h 50m,1 stop,No info,8625
38,Jet Airways,06/03/2019,Banglore,New Delhi,BLR → BOM → DEL,07:00,13:15,6h 15m,1 stop,No info,19225
58,Multiple carriers,6/05/2019,Delhi,Cochin,DEL → BOM → COK,19:00,01:30 07 May,6h 30m,1 stop,No info,8073
72,Multiple carriers,24/06/2019,Delhi,Cochin,DEL → BOM → COK,11:40,19:00,7h 20m,1 stop,In-flight meal not included,10791
102,Jet Airways,24/06/2019,Delhi,Cochin,DEL → BOM → COK,20:55,04:25 25 Jun,7h 30m,1 stop,In-flight meal not included,10262
106,Multiple carriers,27/03/2019,Delhi,Cochin,DEL → BOM → COK,11:40,18:50,7h 10m,1 stop,No info,11421
130,Air India,21/03/2019,Banglore,New Delhi,BLR → MAA → DEL,11:50,19:50,8h,1 stop,No info,5932
140,Multiple carriers,9/04/2019,Delhi,Cochin,DEL → BOM → COK,17:30,01:30 10 Apr,8h,1 stop,No info,13017
192,IndiGo,24/06/2019,Delhi,Cochin,DEL → HYD → COK,16:10,22:30,6h 20m,1 stop,No info,6412
232,Air India,18/05/2019,Delhi,Cochin,DEL → BOM → COK,13:00,19:15,6h 15m,1 stop,No info,10191
273,Multiple carriers,6/06/2019,Delhi,Cochin,DEL → IXU → BOM → COK,17:50,01:30 07 Jun,7h 40m,2 stops,No info,18275
285,Multiple carriers,27/05/2019,Delhi,Cochin,DEL → BOM → COK,17:30,01:30 28 May,8h,1 stop,In-flight meal not included,7308
288,Jet Airways,27/05/2019,Delhi,Cochin,DEL → BOM → COK,20:55,04:25 28 May,7h 30m,1 stop,In-flight meal not included,12898
306,Jet Airways,15/03/2019,Banglore,New Delhi,BLR → BOM → DEL,08:00,15:15,7h 15m,1 stop,In-flight meal not included,9134
317,Multiple carriers,27/06/2019,Delhi,Cochin,DEL → BOM → COK,19:00,01:30 28 Jun,6h 30m,1 stop,No info,7198
331,IndiGo,21/03/2019,Delhi,Cochin,DEL → HYD → COK,14:20,22:20,8h,1 stop,No info,6528
337,Jet Airways,3/06/2019,Delhi,Cochin,DEL → JDH → BOM → COK,11:40,19:00,7h 20m,2 stops,No info,18804
339,Jet Airways,27/05/2019,Delhi,Cochin,DEL → BOM → COK,11:30,19:00,7h 30m,1 stop,No info,16079
341,Multiple carriers,27/05/2019,Delhi,Cochin,DEL → BOM → COK,17:45,01:30 28 May,7h 45m,1 stop,No info,6795
396,Multiple carriers,1/03/2019,Delhi,Cochin,DEL → BOM → COK,12:50,19:15,6h 25m,1 stop,No info,36983
408,Multiple carriers,3/06/2019,Delhi,Cochin,DEL → BOM → COK,13:00,19:15,6h 15m,1 stop,No info,14848
421,Jet Airways,18/05/2019,Kolkata,Banglore,CCU → BOM → BLR,08:25,16:20,7h 55m,1 stop,In-flight meal not included,10844
427,Multiple carriers,15/05/2019,Delhi,Cochin,DEL → BOM → COK,11:30,19:15,7h 45m,1 stop,No info,14323
438,Multiple carriers,9/04/2019,Delhi,Cochin,DEL → BOM → COK,12:50,19:15,6h 25m,1 stop,No info,6481
454,IndiGo,6/06/2019,Delhi,Cochin,DEL → HYD → COK,05:05,12:10,7h 5m,1 stop,No info,6818
467,Multiple carriers,9/06/2019,Delhi,Cochin,DEL → BOM → COK,19:00,01:30 10 Jun,6h 30m,1 stop,No info,7408
473,Jet Airways,6/03/2019,Delhi,Cochin,DEL → BOM → COK,22:20,04:25 07 Mar,6h 5m,1 stop,In-flight meal not included,12583
481,Multiple carriers,18/05/2019,Delhi,Cochin,DEL → BOM → COK,14:00,21:00,7h,1 stop,No info,13727
486,Jet Airways,01/03/2019,Banglore,New Delhi,BLR → BOM → DEL,08:55,15:15,6h 20m,1 stop,No info,26890
496,Jet Airways,6/06/2019,Delhi,Cochin,DEL → BOM → COK,20:55,04:25 07 Jun,7h 30m,1 stop,No info,14714
503,Air India,6/06/2019,Delhi,Cochin,DEL → BOM → COK,13:00,19:15,6h 15m,1 stop,No info,8372
512,Jet Airways,21/03/2019,Banglore,New Delhi,BLR → BOM → DEL,08:55,16:10,7h 15m,1 stop,In-flight meal not included,7832
524,Jet Airways,21/03/2019,Banglore,New Delhi,BLR → BOM → DEL,08:00,15:15,7h 15m,1 stop,In-flight meal not included,7832
543,Jet Airways,24/03/2019,Kolkata,Banglore,CCU → BOM → BLR,08:25,16:20,7h 55m,1 stop,No info,13759
559,Jet Airways,15/05/2019,Kolkata,Banglore,CCU → DEL → BLR,17:00,23:35,6h 35m,1 stop,No info,14151
562,Multiple carriers,15/06/2019,Delhi,Cochin,DEL → BOM → COK,18:00,01:30 16 Jun,7h 30m,1 stop,No info,7408
574,IndiGo,27/05/2019,Delhi,Cochin,DEL → HYD → COK,05:05,12:10,7h 5m,1 stop,No info,6600
585,IndiGo,15/06/2019,Delhi,Cochin,DEL → HYD → COK,08:35,16:10,7h 35m,1 stop,No info,6442
596,SpiceJet,21/03/2019,Banglore,New Delhi,BLR → PNQ → DEL,10:20,18:15,7h 55m,1 stop,No info,7139
600,Multiple carriers,18/05/2019,Delhi,Cochin,DEL → BOM → COK,11:40,19:15,7h 35m,1 stop,No info,9211
619,Multiple carriers,1/05/2019,Delhi,Cochin,DEL → BOM → COK,19:00,01:30 02 May,6h 30m,1 stop,No info,9424
624,IndiGo,6/03/2019,Delhi,Cochin,DEL → HYD → COK,14:20,22:20,8h,1 stop,No info,7451
628,Jet Airways,15/03/2019,Banglore,New Delhi,BLR → BOM → DEL,22:55,05:05 13 Mar,6h 10m,1 stop,No info,27210
629,Jet Airways,18/05/2019,Kolkata,Banglore,CCU → BOM → BLR,21:10,04:40 19 May,7h 30m,1 stop,No info,13941
652,Jet Airways,06/03/2019,Banglore,New Delhi,BLR → BOM → DEL,05:45,13:15,7h 30m,1 stop,No info,19225
661,Jet Airways,27/03/2019,Delhi,Cochin,DEL → BOM → COK,21:50,04:25 28 Mar,6h 35m,1 stop,In-flight meal not included,6017
662,Jet Airways,9/06/2019,Delhi,Cochin,DEL → BOM → COK,11:30,19:00,7h 30m,1 stop,No info,14714
685,GoAir,12/06/2019,Delhi,Cochin,DEL → AMD → COK,07:25,13:35,6h 10m,1 stop,No info,5842
691,Multiple carriers,27/06/2019,Delhi,Cochin,DEL → HYD → COK,14:55,22:30,7h 35m,1 stop,In-flight meal not included,6093

In [34]:
# Load the label encoders and the scaler
label_encoders = joblib.load(r'C:\Projects\DataSci\ML\TicketPrice\live_model\model_outputs\label_encoders.pkl')
scaler = joblib.load(r'C:\Projects\DataSci\ML\TicketPrice\live_model\model_outputs\scaler.pkl')

#use encoders and scaler to transform the input data

In [35]:
#convert 01:10 22 Mar in arrival time to hh:mm format
raw['Arrival_Time'] = raw['Arrival_Time'].str.split(' ').str[0]
raw['Arrival_Time'] = pd.to_datetime(raw['Arrival_Time'],
                                     format='%H:%M').dt.strftime('%H:%M')       

raw['Dep_Time'] = raw['Dep_Time'].str.split(' ').str[0]
raw['Dep_Time'] = pd.to_datetime(raw['Dep_Time'],
                                 format='%H:%M').dt.strftime('%H:%M')

In [36]:
x, y, label_encoders, scaler = preprocess_data(raw, label_encoders=label_encoders, scaler=scaler)

Warning: There are NaN values in the 'Total_Stops' column after mapping.

In [38]:
x_test = x
y_test = y

In [ ]:
#find nan values in x_test
x_test.isna().sum()

Airline            0
Source             0
Destination        0
Route              0
Duration           0
Total_Stops        0
Additional_Info    0
Journey_day        0
Journey_month      0
Dep_hour           0
Dep_minute         0
Arrival_hour       0
Arrival_minute     0
dtype: int64

In [40]:
x_test = x_test.fillna(0)

In [26]:
model_1 = joblib.load(r'C:\Projects\DataSci\ML\TicketPrice\live_model\model_outputs\meta_model.pkl')

In [42]:
result = model_1.predict(x_test)
print(result)

UserWarning: X has feature names, but LinearRegression was fitted without feature names

ValueError: X has 13 features, but LinearRegression is expecting 3 features as input.